spring:
  cloud:
    gateway:
      routes:
      - id: spring-cloud-sleuth
        uri: http://localhost:8080
        predicates:
          - Path=/payment-service/**
      - id: insurance-provider
        uri: http://localhost:8081
        predicates:
          - Path=/insurance-service/**